# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [6]:
import numpy as np
x = np.zeros((10))
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [8]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [9]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [10]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [12]:
np.version.version

'1.18.1'

7. Print the dimension of the array in question 3


In [4]:
import numpy as np
x = np.arange(10,50)
print(x.ndim)

1


8. Create a boolean array with all the True values

In [5]:
x = np.arange(20,50,3)
x>5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [18]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

10. Create a three dimensional array



In [22]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [21]:
import numpy as np
y = list(range(5,25,2))
print(y)
z = np.array(y)
y = np.flip(z)
y

[5, 7, 9, 11, 13, 15, 17, 19, 21, 23]


array([23, 21, 19, 17, 15, 13, 11,  9,  7,  5])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
import numpy as np
x = np.zeros(10)
x
print("Updating fifth value: ")
x[4]=1
x

Updating fifth value: 


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [24]:
import numpy as np
identity = np.identity(3)
print("3X3 IDENTITY MATRIX: ")
print(identity)

3X3 IDENTITY MATRIX: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [30]:
import numpy as np
l = list(range(5,45,7))
z = np.array(l)
z = z.astype("float64")
z.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [23]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [2]:
import numpy as np
arr1 = np.array([[1.,2.,3.], [4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
print("Original Arrays: ")
print(arr1)
print(arr2)
print("Comparison - Equal:")
print(np.equal(arr1,arr2))

Original Arrays: 
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
Comparison - Equal:
[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [7]:
l = list(range(1,10))
x = np.array(l)
print(x)
odd_numbers = (x%2==1)
x[odd_numbers]

[1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [8]:
l = list(range(1,10))
z = np.array(l)
print(l)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [6]:
arr = np.arange(1,10,1)
print(arr)
arr[4:7]=8
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 8 8 8 8 9]


20. Create a 2d array with 1 on the border and 0 inside

In [18]:
import numpy as np
z = np.ones((5,5))
print(z)
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [1]:
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.where(arr2d==5,12,arr2d))

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [20]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [15]:
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0]

array([1, 2, 3])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [40]:
arr2d = np.array([[1,2,3,4,5,6],[7,8,9]])
print("2D array: ", arr2d)
print(arr2d[1][1])

2D array:  [list([1, 2, 3, 4, 5, 6]) list([7, 8, 9])]
8


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [72]:
arr3d = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print("2D array: ", arr3d)
print("Silicing third")
print(arr3d[0:2,2])

2D array:  [[0 1 2 3 4]
 [5 6 7 8 9]]
Silicing third
[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
import numpy as np
rand = np.random.randn(10,10)
print(rand)
np.amax(rand)

[[-0.01707523 -1.58703987 -1.33558321 -0.11200509  0.3780938   0.47432178
   0.26821593  0.12424232 -0.86390432  0.69689044]
 [-0.95016969  1.56336326  0.13537324  0.19769117 -1.33732746 -0.2406267
  -0.45061456  0.53661142  1.05849394 -0.15730337]
 [-0.70877646  0.17214125 -0.030322    0.65929666  0.65351891 -1.15379618
   0.57333813  1.90726004 -1.50384745  0.26250801]
 [-0.13932068 -0.28650017 -1.01803628 -1.20983391  2.35011577  0.90520141
   2.25278755 -0.37154272 -0.76539633  0.34596432]
 [-2.38095506  0.57913174 -0.99135676 -0.53313722  0.90410294 -0.64196752
   1.18936927 -1.0483392   0.85445729 -0.71085773]
 [ 0.78202938  0.25394059  0.91348801  0.45858227 -0.30299038  1.96619605
   1.39066014 -0.40131593 -0.96278807 -0.01747364]
 [-0.9804585   1.63849091  0.57818989  1.33078626 -0.84650509  0.60064509
  -1.29625635 -0.85175364 -0.6830497   0.91392195]
 [-0.60158759 -0.3785599   1.2425563   0.08233916 -0.12406014  0.27176862
   0.42604885  1.60991759  0.03535565  1.07166359]
 

2.3501157659976504

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [29]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [7]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.where(a==b)
print(result)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [12]:
import numpy as np 
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print("Names",names)
print("Data", data)
data[names!='Will']

Names ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Data [[ 0.94949578 -1.30655993  1.0352503   1.43507165]
 [ 2.09623499 -1.94112963 -1.05335321 -1.53781703]
 [ 0.18932913 -0.82428473  1.20794172 -0.56552062]
 [-0.69916377 -0.02744472  1.30325922  0.87281846]
 [ 0.56192456  0.43681614  0.78753615 -0.07031271]
 [ 1.86502656  0.03019744 -1.01735594  1.6730247 ]
 [-0.53894479 -0.32194558 -0.07327495  1.31770276]]


array([[ 0.94949578, -1.30655993,  1.0352503 ,  1.43507165],
       [ 2.09623499, -1.94112963, -1.05335321, -1.53781703],
       [-0.69916377, -0.02744472,  1.30325922,  0.87281846],
       [ 1.86502656,  0.03019744, -1.01735594,  1.6730247 ],
       [-0.53894479, -0.32194558, -0.07327495,  1.31770276]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [15]:
import numpy as np
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print("Names", names)
print("Data", data)
data[names!=np.any('Will','Joe')]

Names ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Data [[-0.95779186  0.19276941  1.1136026  -0.48575115]
 [ 1.95028303 -0.292634    1.38397212  0.41489638]
 [ 1.43424697  0.08480785  0.54849078 -0.58786047]
 [-0.86348656  0.97324909 -1.08110865 -0.36274453]
 [-1.37356365 -0.28290968 -0.50405566 -0.04884183]
 [ 0.45611654 -0.23351149 -1.16098989  1.34910249]
 [ 0.78190708 -0.18090942 -0.07326244  0.2978436 ]]


TypeError: cannot perform reduce with flexible type

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [11]:
import numpy as np
arr2d = np.random.uniform(low=1, high=15, size=(5,3))
print(arr2d)

[[14.55289841  8.40870244  3.24717178]
 [13.50242288 14.82841333 11.77973256]
 [ 6.69424785  2.65818475 11.73590674]
 [ 3.88049241 13.0447222  10.4241366 ]
 [14.31155646  3.67130721  2.13052093]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [12]:
import numpy as np
arr = np.random.uniform(low=1,high=15,size=(2,2,4))
print(arr)

[[[ 8.78327801 13.60949009  4.02986559  7.8852605 ]
  [ 3.78253048 11.00670303 11.87073732  1.29719016]]

 [[13.42025208  7.44503245 10.80337771 13.29089055]
  [ 7.37615447  3.16239394 14.6488748   5.26694015]]]


33. Swap axes of the array you created in Question 32

In [14]:
print(arr)
print("After swapping arr axis 0 with 2")
swap = np.swapaxes(arr,0,2)
print(swap)

[[[ 8.78327801 13.60949009  4.02986559  7.8852605 ]
  [ 3.78253048 11.00670303 11.87073732  1.29719016]]

 [[13.42025208  7.44503245 10.80337771 13.29089055]
  [ 7.37615447  3.16239394 14.6488748   5.26694015]]]
After swapping arr axis 0 with 2
[[[ 8.78327801 13.42025208]
  [ 3.78253048  7.37615447]]

 [[13.60949009  7.44503245]
  [11.00670303  3.16239394]]

 [[ 4.02986559 10.80337771]
  [11.87073732 14.6488748 ]]

 [[ 7.8852605  13.29089055]
  [ 1.29719016  5.26694015]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [20]:
import numpy as np
arr = np.random.uniform(10)
sqrt = np.sqrt([-0.82533994,  0.13639128,  1.17944442, -0.58921866, -1.21288983,
       -0.3768371 ,  0.86276891,  1.31932418,  1.24396707, -2.07373226])
sqrt

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.


array([       nan, 0.3693119 , 1.08602229,        nan,        nan,
              nan, 0.92885355, 1.14861838, 1.11533272,        nan])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [28]:
import numpy as np
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
print("Array 1 ", arr1, sep="\n")
print("Array2 ", arr2)
new_array = np.maximum(arr1,arr2)
print("\nMaximum values ", new_array)

Array 1 
[ 0.94455699 -1.52724684  1.87649167 -2.19617977 -1.53684966 -0.14945056
 -0.3873801   0.91846636 -0.27066151  0.38750534  0.50224582 -0.82065654]
Array2  [-0.85740258  0.12502714  0.72055423  0.62139794  0.05339613  0.7119846
  0.53661089 -1.71870168  0.02659199  1.29354306 -0.39018252  0.72442769]

Maximum values  [0.94455699 0.12502714 1.87649167 0.62139794 0.05339613 0.7119846
 0.53661089 0.91846636 0.02659199 1.29354306 0.50224582 0.72442769]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [3]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

result = np.unique(names)
print(result)
result.sort()

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [65]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [9]:
import numpy as numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
result = numpy.delete(sampleArray,1,axis=1)
print("After deleting the 2nd column of the array")
print(result)
newColumn = numpy.array([[10,10,10]])
insert = numpy.insert(result,1,newColumn,axis=1)
print("After inserting the new column in the matrix")
print(insert)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
After deleting the 2nd column of the array
[[34 73]
 [82 12]
 [53 66]]
After inserting the new column in the matrix
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [1]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot = np.dot(x,y)
print("The dot product of two matrices is: ", dot)

The dot product of two matrices is:  [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [4]:
import numpy as np
arr = np.random.randn(20)
print(arr)
print("Now finding the cumulative sum of the matrix we created: ")
print(np.cumsum(arr))

[-1.14398045  0.9505208  -1.09774571  0.95200632  0.00836856 -0.93499624
  0.20292907  2.19778603 -0.8520088  -2.6645055  -0.78361626  0.26386063
 -1.38125703 -0.54110325  2.15562284  0.71832153  2.15916847 -0.61599788
  0.87379788  0.23710528]
Now finding the cumulative sum of the matrix we created: 
[-1.14398045 -0.19345965 -1.29120536 -0.33919904 -0.33083048 -1.26582673
 -1.06289766  1.13488837  0.28287956 -2.38162594 -3.1652422  -2.90138157
 -4.28263859 -4.82374184 -2.668119   -1.94979747  0.209371   -0.40662688
  0.46717101  0.70427629]
